import { prisma } from "@/lib/prisma";
import { DeterministicReportService } from "./DeterministicReportService";
import { ReportStatus } from "@prisma/client";
import { AuditLogService } from "./AuditLogService";

export class ReportService {
  /**
   * Get existing daily report or generate deterministic draft
   */
  static async getOrCreateDailyReport(userId: string, workDate: string) {
    const existing = await prisma.dailyReport.findUnique({
      where: {
        userId_workDate: { userId, workDate },
      },
    });

    if (existing) {
      return existing;
    }

    // Generate fresh from database records
    const rawData = await DeterministicReportService.generateDailyReport(userId, workDate);

    const report = await prisma.dailyReport.create({
      data: {
        userId,
        workDate,
        startedAt: rawData.startedAt,
        endedAt: rawData.endedAt,
        totalSessionSec: rawData.totalSessionSec,
        totalBreakSec: rawData.totalBreakSec,
        netWorkSec: rawData.netWorkSec,
        completedWorkJson: JSON.stringify(rawData.completedWork),
        inProgressJson: JSON.stringify(rawData.inProgress),
        pendingTasksJson: JSON.stringify(rawData.pendingTasks),
        meetingsJson: JSON.stringify(rawData.meetings),
        blockersJson: JSON.stringify(rawData.blockers),
        achievementsJson: JSON.stringify(rawData.achievements),
        recommendedNextSteps: rawData.recommendedNextSteps,
        status: ReportStatus.DRAFT,
        isAutoGenerated: true,
        isUserEdited: false,
      },
    });

    return report;
  }

  /**
   * Regenerate report draft from latest live records
   */
  static async refreshDailyReport(userId: string, workDate: string) {
    const rawData = await DeterministicReportService.generateDailyReport(userId, workDate);

    const updated = await prisma.dailyReport.upsert({
      where: {
        userId_workDate: { userId, workDate },
      },
      update: {
        startedAt: rawData.startedAt,
        endedAt: rawData.endedAt,
        totalSessionSec: rawData.totalSessionSec,
        totalBreakSec: rawData.totalBreakSec,
        netWorkSec: rawData.netWorkSec,
        completedWorkJson: JSON.stringify(rawData.completedWork),
        inProgressJson: JSON.stringify(rawData.inProgress),
        pendingTasksJson: JSON.stringify(rawData.pendingTasks),
        meetingsJson: JSON.stringify(rawData.meetings),
        blockersJson: JSON.stringify(rawData.blockers),
        achievementsJson: JSON.stringify(rawData.achievements),
        recommendedNextSteps: rawData.recommendedNextSteps,
      },
      create: {
        userId,
        workDate,
        startedAt: rawData.startedAt,
        endedAt: rawData.endedAt,
        totalSessionSec: rawData.totalSessionSec,
        totalBreakSec: rawData.totalBreakSec,
        netWorkSec: rawData.netWorkSec,
        completedWorkJson: JSON.stringify(rawData.completedWork),
        inProgressJson: JSON.stringify(rawData.inProgress),
        pendingTasksJson: JSON.stringify(rawData.pendingTasks),
        meetingsJson: JSON.stringify(rawData.meetings),
        blockersJson: JSON.stringify(rawData.blockers),
        achievementsJson: JSON.stringify(rawData.achievements),
        recommendedNextSteps: rawData.recommendedNextSteps,
        status: ReportStatus.DRAFT,
      },
    });

    return updated;
  }

  /**
   * Save user edits and/or submit the daily report
   */
  static async submitDailyReport(
    userId: string,
    workDate: string,
    data: {
      notes?: string;
      recommendedNextSteps?: string;
      completedWorkJson?: string;
      inProgressJson?: string;
      status?: ReportStatus;
    }
  ) {
    const report = await this.getOrCreateDailyReport(userId, workDate);

    const isUserEdited = Boolean(
      (data.notes !== undefined && data.notes !== report.notes) ||
      (data.recommendedNextSteps !== undefined && data.recommendedNextSteps !== report.recommendedNextSteps) ||
      (data.completedWorkJson !== undefined && data.completedWorkJson !== report.completedWorkJson)
    );

    const updated = await prisma.dailyReport.update({
      where: { id: report.id },
      data: {
        notes: data.notes ?? report.notes,
        recommendedNextSteps: data.recommendedNextSteps ?? report.recommendedNextSteps,
        completedWorkJson: data.completedWorkJson ?? report.completedWorkJson,
        inProgressJson: data.inProgressJson ?? report.inProgressJson,
        status: data.status || ReportStatus.SUBMITTED,
        submittedAt: data.status === ReportStatus.SUBMITTED ? new Date() : report.submittedAt,
        isUserEdited: isUserEdited || report.isUserEdited,
      },
    });

    await AuditLogService.log({
      userId,
      action: "DAILY_REPORT_SUBMIT",
      entity: "DailyReport",
      entityId: updated.id,
      metadata: { workDate, status: updated.status, isUserEdited: updated.isUserEdited },
    });

    return updated;
  }

  /**
   * List reports for an employee
   */
  static async listUserReports(userId: string) {
    return prisma.dailyReport.findMany({
      where: { userId },
      orderBy: { workDate: "desc" },
    });
  }
}
